//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdleMaster.localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdleMaster.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;About 的本地化字符串。
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Accept 的本地化字符串。
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Add 的本地化字符串。
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Game to Blacklist 的本地化字符串。
        /// </summary>
        internal static string add_game_blacklist {
            get {
                return ResourceManager.GetString("add_game_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display advanced authentication information 的本地化字符串。
        /// </summary>
        internal static string advanced_auth {
            get {
                return ResourceManager.GetString("advanced_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Master Authentication Data 的本地化字符串。
        /// </summary>
        internal static string auth_data {
            get {
                return ResourceManager.GetString("auth_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Badge page didn&apos;t load, will retry in __num__ seconds 的本地化字符串。
        /// </summary>
        internal static string badge_didnt_load {
            get {
                return ResourceManager.GetString("badge_didnt_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Blacklist 的本地化字符串。
        /// </summary>
        internal static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Blacklist Current Game 的本地化字符串。
        /// </summary>
        internal static string blacklist_current_game {
            get {
                return ResourceManager.GetString("blacklist_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Cancel 的本地化字符串。
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 card drops remaining 的本地化字符串。
        /// </summary>
        internal static string card_drops_remaining {
            get {
                return ResourceManager.GetString("card_drops_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display information above
        ///
        ///[WARNING]
        ///Do not share this information with anyone,
        ///as it could potentially be used by an attacker to log into
        ///your Steam account. 的本地化字符串。
        /// </summary>
        internal static string cookie_warning {
            get {
                return ResourceManager.GetString("cookie_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently in-game 的本地化字符串。
        /// </summary>
        internal static string currently_ingame {
            get {
                return ResourceManager.GetString("currently_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E&amp;xit 的本地化字符串。
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;File 的本地化字符串。
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Game 的本地化字符串。
        /// </summary>
        internal static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 games left to idle 的本地化字符串。
        /// </summary>
        internal static string games_left_to_idle {
            get {
                return ResourceManager.GetString("games_left_to_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Help 的本地化字符串。
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hours 的本地化字符串。
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 hrs on record 的本地化字符串。
        /// </summary>
        internal static string hrs_on_record {
            get {
                return ResourceManager.GetString("hrs_on_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle each game individually 的本地化字符串。
        /// </summary>
        internal static string idle_individual {
            get {
                return ResourceManager.GetString("idle_individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Master is connected to Steam 的本地化字符串。
        /// </summary>
        internal static string idle_master_connected {
            get {
                return ResourceManager.GetString("idle_master_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Master is not connected to Steam 的本地化字符串。
        /// </summary>
        internal static string idle_master_notconnected {
            get {
                return ResourceManager.GetString("idle_master_notconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Master Settings 的本地化字符串。
        /// </summary>
        internal static string idle_master_settings {
            get {
                return ResourceManager.GetString("idle_master_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 idle now 的本地化字符串。
        /// </summary>
        internal static string idle_now {
            get {
                return ResourceManager.GetString("idle_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle games with more than 2 hours individually, then simultaneously 的本地化字符串。
        /// </summary>
        internal static string idle_onethenmany {
            get {
                return ResourceManager.GetString("idle_onethenmany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle games simultaneously up to 2 hours, then individually 的本地化字符串。
        /// </summary>
        internal static string idle_simultaneous {
            get {
                return ResourceManager.GetString("idle_simultaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idling Behavior 的本地化字符串。
        /// </summary>
        internal static string idling_behavior {
            get {
                return ResourceManager.GetString("idling_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idling complete, no more card drops available 的本地化字符串。
        /// </summary>
        internal static string idling_complete {
            get {
                return ResourceManager.GetString("idling_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idling Order 的本地化字符串。
        /// </summary>
        internal static string idling_order {
            get {
                return ResourceManager.GetString("idling_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idling paused 的本地化字符串。
        /// </summary>
        internal static string idling_paused {
            get {
                return ResourceManager.GetString("idling_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Steam client status 的本地化字符串。
        /// </summary>
        internal static string ignore_client_status {
            get {
                return ResourceManager.GetString("ignore_client_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interface Language 的本地化字符串。
        /// </summary>
        internal static string interface_language {
            get {
                return ResourceManager.GetString("interface_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading next game... 的本地化字符串。
        /// </summary>
        internal static string loading_next {
            get {
                return ResourceManager.GetString("loading_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Idle Master Blacklist 的本地化字符串。
        /// </summary>
        internal static string manage_blacklist {
            get {
                return ResourceManager.GetString("manage_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize Idle Master to system tray 的本地化字符串。
        /// </summary>
        internal static string minimize_to_tray {
            get {
                return ResourceManager.GetString("minimize_to_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next check 的本地化字符串。
        /// </summary>
        internal static string next_check {
            get {
                return ResourceManager.GetString("next_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not in game 的本地化字符串。
        /// </summary>
        internal static string not_ingame {
            get {
                return ResourceManager.GetString("not_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Official Group 的本地化字符串。
        /// </summary>
        internal static string official_group {
            get {
                return ResourceManager.GetString("official_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;OK 的本地化字符串。
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default (Alphabetical Order) 的本地化字符串。
        /// </summary>
        internal static string order_default {
            get {
                return ResourceManager.GetString("order_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritize games with the lowest number of available drops 的本地化字符串。
        /// </summary>
        internal static string order_least {
            get {
                return ResourceManager.GetString("order_least", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritize games with the highest number of available drops 的本地化字符串。
        /// </summary>
        internal static string order_most {
            get {
                return ResourceManager.GetString("order_most", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prioritize games with the highest card values 的本地化字符串。
        /// </summary>
        internal static string order_value {
            get {
                return ResourceManager.GetString("order_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Pause Idling 的本地化字符串。
        /// </summary>
        internal static string pause_idling {
            get {
                return ResourceManager.GetString("pause_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Login to Steam 的本地化字符串。
        /// </summary>
        internal static string please_login {
            get {
                return ResourceManager.GetString("please_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please restart the application for language changes to take effect. 的本地化字符串。
        /// </summary>
        internal static string please_restart {
            get {
                return ResourceManager.GetString("please_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please wait... 的本地化字符串。
        /// </summary>
        internal static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading badge page 的本地化字符串。
        /// </summary>
        internal static string reading_badge_page {
            get {
                return ResourceManager.GetString("reading_badge_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Release Notes 的本地化字符串。
        /// </summary>
        internal static string release_notes {
            get {
                return ResourceManager.GetString("release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Master Release Notes 的本地化字符串。
        /// </summary>
        internal static string release_notes_title {
            get {
                return ResourceManager.GetString("release_notes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Resume Idling 的本地化字符串。
        /// </summary>
        internal static string resume_idling {
            get {
                return ResourceManager.GetString("resume_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Save 的本地化字符串。
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle Master is saving your information 的本地化字符串。
        /// </summary>
        internal static string saving_info {
            get {
                return ResourceManager.GetString("saving_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Settings 的本地化字符串。
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Steam username of signed on user 的本地化字符串。
        /// </summary>
        internal static string show_username {
            get {
                return ResourceManager.GetString("show_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Out 的本地化字符串。
        /// </summary>
        internal static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signed in as 的本地化字符串。
        /// </summary>
        internal static string signed_in_as {
            get {
                return ResourceManager.GetString("signed_in_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Skip Current Game 的本地化字符串。
        /// </summary>
        internal static string skip_current_game {
            get {
                return ResourceManager.GetString("skip_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorting results based on your settings, please wait... 的本地化字符串。
        /// </summary>
        internal static string sorting_results {
            get {
                return ResourceManager.GetString("sorting_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Statistics 的本地化字符串。
        /// </summary>
        internal static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam client status ignored 的本地化字符串。
        /// </summary>
        internal static string steam_ignored {
            get {
                return ResourceManager.GetString("steam_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam is not running 的本地化字符串。
        /// </summary>
        internal static string steam_notrunning {
            get {
                return ResourceManager.GetString("steam_notrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steam is running 的本地化字符串。
        /// </summary>
        internal static string steam_running {
            get {
                return ResourceManager.GetString("steam_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Session 的本地化字符串。
        /// </summary>
        internal static string this_session {
            get {
                return ResourceManager.GetString("this_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Update 的本地化字符串。
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update games status 的本地化字符串。
        /// </summary>
        internal static string update_games_status {
            get {
                return ResourceManager.GetString("update_games_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data you&apos;ve entered isn&apos;t valid.  Please try again. 的本地化字符串。
        /// </summary>
        internal static string validate_failed {
            get {
                return ResourceManager.GetString("validate_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validating... 的本地化字符串。
        /// </summary>
        internal static string validating {
            get {
                return ResourceManager.GetString("validating", resourceCulture);
            }
        }
    }
}
